---
name: build and publish

on:
  push:
    branches:
      - release
env:
  S3_BUCKET: playground.dataverse-os.com

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build and release dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.28.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: pnpm build
        run: pnpm run github-build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs:
      - build
    name: Deploy dist to AWS S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::164331695891:role/GitHubAction
          aws-region: ap-east-1

      - name: Copy files to the S3 bucket
        run: |
          aws s3 sync dist s3://${{ env.S3_BUCKET }}
